"""
CHALLENGE: Build a Multi-Pass Review Architecture
==================================================
Task Statement 4.6 — Design multi-instance and multi-pass review architectures

Design a review system for a multi-file pull request that avoids
self-review bias and attention dilution.

Instructions:
    Implement each method in the MultiPassChallenge class.
    Run the checker to validate your implementation:
        python checker.py

Hints:
    - Self-review bias occurs when the generating instance reviews its own
      code — it retains reasoning context and cannot question its own
      assumptions objectively.
    - Independent review means a new instance that receives ONLY the code,
      not the generation conversation.
    - Attention dilution occurs when many files are reviewed in a single
      pass — earlier files get more attention than later ones.
    - Per-file local passes + a cross-file integration pass prevents this.
"""


class MultiPassChallenge:
    """Multi-pass code review architecture."""

    def should_use_independent_review(self, context: dict) -> bool:
        """
        Decide whether an independent review instance is needed.

        Args:
            context: A dict with keys:
                - "generated_in_session" (bool): True if the code was
                  generated by Claude in the current conversation session.
                - "file_count" (int): number of files in the PR.
                - "is_critical" (bool): True if the code touches critical
                  paths (auth, payments, data deletion, etc.).

        Returns:
            True if an independent instance should be used for review.

        Rules:
            - If code was generated in this session, ALWAYS use independent
              review (self-review bias makes same-session review unreliable).
            - If the code is critical, ALWAYS use independent review
              (the stakes are too high for same-session review).
            - If file_count > 3, use independent review (large PRs benefit
              from unbiased evaluation).
            - Otherwise, same-session review is acceptable.
        """
        # TODO: Implement this method
        pass

    def split_into_passes(self, files: list[dict]) -> dict:
        """
        Split a list of PR files into local and integration review passes.

        Args:
            files: A list of file dicts, each with:
                - "name" (str): filename (e.g., "auth/login.py")
                - "content" (str): file source code
                - "imports" (list[str]): list of modules this file imports
                  from within the PR (e.g., ["auth/session.py"])

        Returns:
            A dict with two keys:
                "local_passes": a list of dicts, one per file, each with:
                    - "file": the original file dict
                    - "pass_type": "local"
                "integration_pass": a dict with:
                    - "files": the full list of file dicts
                    - "cross_file_pairs": a list of [importer, imported]
                      pairs where one file imports another. Each pair is
                      a list of two filename strings.
                    - "pass_type": "integration"

        Example cross_file_pairs:
            If auth/login.py imports auth/session.py, include:
            ["auth/login.py", "auth/session.py"]
        """
        # TODO: Implement this method
        pass

    def build_local_review_prompt(self, file: dict) -> str:
        """
        Build a focused review prompt for a single file.

        Args:
            file: A file dict with "name" (str) and "content" (str).

        Returns:
            A prompt string that:
            1. Starts with "Review the following file for bugs, edge cases, "
               "and design issues."
            2. Contains the filename.
            3. Contains the file content inside a code block.
            4. Instructs the reviewer to focus ONLY on issues within this
               single file (not cross-file concerns).
            5. Asks for findings as a structured list.

        The exact format must be:
            Review the following file for bugs, edge cases, and design issues.
            Focus ONLY on issues within this single file.

            Filename: {name}
            ```
            {content}
            ```

            List your findings as bullet points. For each finding include:
            - Category (bug, edge case, style, performance)
            - Severity (high, medium, low)
            - Description
        """
        # TODO: Implement this method
        pass

    def build_integration_review_prompt(
        self, files: list[dict], local_findings: list[dict]
    ) -> str:
        """
        Build a cross-file integration review prompt.

        Args:
            files: The full list of file dicts (name, content, imports).
            local_findings: A list of dicts from local reviews, each with:
                - "file" (str): filename
                - "findings" (str): the review output text

        Returns:
            A prompt string that:
            1. Starts with "You are reviewing a {N}-file pull request."
               where {N} is len(files).
            2. States that per-file reviews are already completed.
            3. Instructs the reviewer to focus ONLY on cross-file issues:
               data flow, API contracts, and shared state.
            4. Includes the local findings summary for each file.
            5. Includes the filename and content for each file.

        The exact format must be:
            You are reviewing a {N}-file pull request.
            Per-file reviews have already been completed.
            Focus ONLY on cross-file issues: data flow between modules,
            API contract mismatches, and shared state mutations.

            == Per-File Findings ==
            --- {filename} ---
            {findings}
            (repeated for each file)

            == File Contents ==
            --- {filename} ---
            ```
            {content}
            ```
            (repeated for each file)
        """
        # TODO: Implement this method
        pass

    def merge_findings(
        self, local_findings: list[dict], integration_findings: list[dict]
    ) -> list[dict]:
        """
        Merge local and integration findings, deduplicating by description.

        Args:
            local_findings: list of finding dicts, each with:
                - "file" (str): filename where the issue was found
                - "category" (str): e.g., "bug", "edge case"
                - "severity" (str): "high", "medium", or "low"
                - "description" (str): description of the issue
            integration_findings: same structure, but from integration pass.
                The "file" field may contain multiple filenames separated
                by ", " (e.g., "auth/login.py, auth/session.py").

        Returns:
            A merged list of finding dicts with duplicates removed.
            - Two findings are duplicates if their "description" values
              are identical (case-insensitive comparison).
            - When duplicates exist, prefer the integration finding
              (it has better cross-file context).
            - Sort the final list by severity: high first, then medium,
              then low.

        Example:
            local:       [{"description": "Missing null check", ...}]
            integration: [{"description": "missing null check", ...}]
            result:      keeps only the integration version (case-insensitive match)
        """
        # TODO: Implement this method
        pass


# ── Test Data ────────────────────────────────────────────────────────────

SAMPLE_FILES = [
    {
        "name": "auth/login.py",
        "content": (
            "from auth.session import create_session\n"
            "\n"
            "def login(username, password):\n"
            "    user = db.find_user(username)\n"
            "    if user and user.check_password(password):\n"
            "        return create_session(user)\n"
            "    return None\n"
        ),
        "imports": ["auth/session.py"],
    },
    {
        "name": "auth/session.py",
        "content": (
            "import time\n"
            "\n"
            "SESSION_TTL = 3600\n"
            "\n"
            "def create_session(user):\n"
            "    return {\n"
            "        'user_id': user.id,\n"
            "        'created_at': time.time(),\n"
            "        'expires_at': time.time() + SESSION_TTL\n"
            "    }\n"
            "\n"
            "def is_valid(session):\n"
            "    return session['expires_at'] > time.time()\n"
        ),
        "imports": [],
    },
    {
        "name": "auth/middleware.py",
        "content": (
            "from auth.session import is_valid\n"
            "\n"
            "def require_auth(handler):\n"
            "    def wrapper(request):\n"
            "        session = request.get_session()\n"
            "        if not session or not is_valid(session):\n"
            "            return {'status': 401}\n"
            "        return handler(request)\n"
            "    return wrapper\n"
        ),
        "imports": ["auth/session.py"],
    },
    {
        "name": "api/routes.py",
        "content": (
            "from auth.middleware import require_auth\n"
            "from auth.login import login\n"
            "\n"
            "@require_auth\n"
            "def get_profile(request):\n"
            "    return {'user': request.user}\n"
            "\n"
            "def post_login(request):\n"
            "    session = login(request.body['username'], request.body['password'])\n"
            "    if session:\n"
            "        return {'status': 200, 'session': session}\n"
            "    return {'status': 401}\n"
        ),
        "imports": ["auth/middleware.py", "auth/login.py"],
    },
]

SAMPLE_CONTEXTS = [
    {
        "generated_in_session": True,
        "file_count": 4,
        "is_critical": True,
    },
    {
        "generated_in_session": False,
        "file_count": 2,
        "is_critical": False,
    },
    {
        "generated_in_session": False,
        "file_count": 8,
        "is_critical": False,
    },
    {
        "generated_in_session": True,
        "file_count": 1,
        "is_critical": False,
    },
    {
        "generated_in_session": False,
        "file_count": 2,
        "is_critical": True,
    },
]

SAMPLE_LOCAL_FINDINGS = [
    {
        "file": "auth/login.py",
        "category": "bug",
        "severity": "high",
        "description": "Missing null check on db.find_user result",
    },
    {
        "file": "auth/session.py",
        "category": "edge case",
        "severity": "medium",
        "description": "SESSION_TTL is hardcoded; should be configurable",
    },
    {
        "file": "auth/middleware.py",
        "category": "style",
        "severity": "low",
        "description": "Wrapper function missing docstring",
    },
    {
        "file": "api/routes.py",
        "category": "bug",
        "severity": "high",
        "description": "post_login does not set session cookie on response",
    },
]

SAMPLE_INTEGRATION_FINDINGS = [
    {
        "file": "auth/login.py, auth/session.py",
        "category": "bug",
        "severity": "high",
        "description": "create_session returns dict but login callers may expect object",
    },
    {
        "file": "auth/middleware.py, auth/session.py",
        "category": "edge case",
        "severity": "medium",
        "description": "is_valid does not handle missing 'expires_at' key gracefully",
    },
    {
        "file": "auth/login.py, auth/session.py",
        "category": "bug",
        "severity": "high",
        "description": "Missing null check on db.find_user result",
    },
]

SAMPLE_LOCAL_REVIEW_OUTPUTS = [
    {
        "file": "auth/login.py",
        "findings": "- [bug/high] Missing null check on db.find_user result\n- [edge case/medium] No rate limiting on login attempts",
    },
    {
        "file": "auth/session.py",
        "findings": "- [edge case/medium] SESSION_TTL is hardcoded; should be configurable",
    },
    {
        "file": "auth/middleware.py",
        "findings": "- [style/low] Wrapper function missing docstring",
    },
    {
        "file": "api/routes.py",
        "findings": "- [bug/high] post_login does not set session cookie on response",
    },
]


if __name__ == "__main__":
    challenge = MultiPassChallenge()

    print("=== Multi-Pass Review Challenge ===\n")

    # Test should_use_independent_review
    print("1. Independent Review Decision:")
    for ctx in SAMPLE_CONTEXTS:
        result = challenge.should_use_independent_review(ctx)
        print(
            f"   generated={ctx['generated_in_session']}, "
            f"files={ctx['file_count']}, "
            f"critical={ctx['is_critical']} -> {result}"
        )

    # Test split_into_passes
    print("\n2. Split Into Passes:")
    passes = challenge.split_into_passes(SAMPLE_FILES)
    if passes:
        print(f"   Local passes: {len(passes.get('local_passes', []))}")
        ip = passes.get("integration_pass", {})
        print(f"   Cross-file pairs: {ip.get('cross_file_pairs', [])}")

    # Test build_local_review_prompt
    print("\n3. Local Review Prompt (first file):")
    prompt = challenge.build_local_review_prompt(SAMPLE_FILES[0])
    if prompt:
        lines = prompt.strip().split("\n")
        print(f"   First line: {lines[0]}")
        print(f"   Total lines: {len(lines)}")

    # Test build_integration_review_prompt
    print("\n4. Integration Review Prompt:")
    int_prompt = challenge.build_integration_review_prompt(
        SAMPLE_FILES, SAMPLE_LOCAL_REVIEW_OUTPUTS
    )
    if int_prompt:
        lines = int_prompt.strip().split("\n")
        print(f"   First line: {lines[0]}")
        print(f"   Total lines: {len(lines)}")

    # Test merge_findings
    print("\n5. Merged Findings:")
    merged = challenge.merge_findings(
        SAMPLE_LOCAL_FINDINGS, SAMPLE_INTEGRATION_FINDINGS
    )
    if merged:
        for f in merged:
            print(f"   [{f['severity']:6s}] {f['file']:45s} {f['description']}")
